### PR TITLE
Fix UI tests for macOS

### LINKED ISSUE #109: Fix UI test for Mac
**Describe the bug**
The user interface of IntelliJ is different on the Mac operating system, the difference causes some of the tests to fail because some of the UI elements are not found. 

**To Reproduce**
1. Get a Mac.
2. Launch the "Run IDE for UI Tests" 
3. Launch the UI test suite, for example, the settings one. 
4. You should see that it successfully opens the untitled project, however, it fails to open the settings panel because it can not find the "File" button. 

As you can see, in the image below the toolbar menu on mac is located on the top and the UI test fails to find that. Furthermore, note how there is an Apple Logo which also skews all of the UI elements as the robot sees it. 

**Expected behavior**
The UI test should be able to enter the settings menu "preferences" on mac and be able to close the project through the file menu. 

**Screenshots**
IntelliJOnMac

**Additional context**

### PR DESCRIPTION
**Pull request by SergeyDatskiv**
# Description of changes made
In this pull request most changes happened in the UI testing classes. Specifically, SettingsComponentTest and QuickAcessParametersTest. Nothing major was changed in terms of logic, there were only changes that made the tests more compatible with the macOS. 
Each change, along with reasoning is documented in the commits, feel free to check those when reviewing. 

# Why is merge request needed
This merge request is needed to adopt the current UI tests to macOS platform. 

# Other notes
Closes #109 

*Please write if you have anything to add*
A few lines were edited that belong to other users. Mainly @kirilvasilev16 and @jzelenjak, I hope that they do not mind that. 

# What is missing?
In order to get the tests to work I had to comment out the @Video annotation in the SettingsComponentTest. I am confused if it is necessary to have that annotation for the GitHub actions or not, because it is used inconsistently throughout the project ( SettingsComponentTest and QuickAcessParametersTest classes)

I didn't run the branch on the GitHub actions and the UI tests on dispatch yet, hence I do not know if the changes actually solve the macOS issue on GitHub actions. I do not know what macOS the GitHub actions are using and therefore it is likely that there could be problems. 

- [x] I have checked that I am merging into correct branch

### CODE REVIEW

File: src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/SettingsComponentTest.kt [hunk 1]
```diff
@@ -210,7 +235,12 @@ class SettingsComponentTest {
 
         // Open settings again
         val ideaFrame = find(IdeaFrame::class.java, timeout = Duration.ofSeconds(15))
-        ideaFrame.openSettings()
```
Comment (kirilvasilev16) [inline src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/SettingsComponentTest.kt:213]: Maybe you can have your change of `ideaFrame.openSettings()` inside the method `openSettings()` to reduce logic duplication?

File: src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/SettingsComponentTest.kt [hunk 2]
```diff
@@ -111,7 +126,7 @@ class SettingsComponentTest {
 
     @Order(5)
     @Test
-    @Video
+    // @Video
```
Comment (kirilvasilev16) [inline src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/SettingsComponentTest.kt:129]: Video not working on mac?

**Review by kirilvasilev16 — CHANGES_REQUESTED** [review]
Tests pass on Windows :)

File: src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/SettingsComponentTest.kt (hunk 2 above)
Comment (SergeyDatskiv) [reply src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/SettingsComponentTest.kt:129]: In order to get the tests to work I had to comment out the @video annotation in the SettingsComponentTest. I am confused if it is necessary to have that annotation for the GitHub actions or not, because it is used inconsistently throughout the project ( SettingsComponentTest and QuickAcessParametersTest classes) - from the description of the pull request.

Comment (SergeyDatskiv) [reply src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/SettingsComponentTest.kt:129]: I don't really know how to run pipeline on dispatch can someone do that for Mac? I can try to add videos back but it doesn't quite work locally for me.

File: src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/SettingsComponentTest.kt (hunk 1 above)
Comment (SergeyDatskiv) [reply src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/SettingsComponentTest.kt:213]: Will try

File: src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/SettingsComponentTest.kt (hunk 2 above)
Comment (kirilvasilev16) [reply src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/SettingsComponentTest.kt:129]: I run your pipeline on dispatch for Windows and it passed :)

Comment (SergeyDatskiv) [reply src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/SettingsComponentTest.kt:129]: Good what about Mac?

File: src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/pages/IdeaFrame.kt [hunk 3]
```diff
@@ -51,9 +55,23 @@ class IdeaFrame(remoteRobot: RemoteRobot, remoteComponent: RemoteComponent) :
     /**
      * Method to open the settings of IntelliJ.
      */
-    fun openSettings() {
-        openFileMenu.click()
-        openSettingsAction.click()
+    fun openSettings(toolWindowOpen: Boolean) {
```
Comment (bolkhod) [inline src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/pages/IdeaFrame.kt:58]: Looks like pure pain, but I like your solution(s)

File: src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/SettingsComponentTest.kt (hunk 1 above)
Comment (SergeyDatskiv) [reply src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/SettingsComponentTest.kt:213]: I think I resolved your comment. If that's what you wanted. However, I ran into a flaky test that I am trying to fix now. 😅

**Review by jzelenjak — APPROVED** [review]
`QuickAccessParametersTest` passes for people who use Arch btw.
`SettingsComponentTest` has one failing test `findEvoSuiteTabExists`, but it passes on WIndows on dispatch and also was there even before. It will be handled in another PR and is not related to you.

It is amazing that you have fixed the tests for Mac. Expecially, given that our clients and many TU Delft employees use Mac

File: src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/SettingsComponentTest.kt (hunk 2 above)
Comment (kirilvasilev16) [reply src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/SettingsComponentTest.kt:113]: Unfortunatelly, we are still in the process of making the dispatch run on Mac/Linux :)

**Review by kirilvasilev16 — DISMISSED** [review]

**Review by jzelenjak — APPROVED** [review]

**Review by kirilvasilev16 — APPROVED** [review]
