### PR TITLE
Fix syntax errors being shown in tool window

### LINKED ISSUE #55: Generated tests tool window shows syntax errors
**Describe the bug**
When the generated tests tool window is updated, it shows an "Unexpected tokens" syntax error over all tests.

**To Reproduce**
1. Generate tests for a class or a method
2. Open a different tool window alongside TestGenie's (e.g. the Maven tool window)
3. Look at the syntax errors and red underlining in the generated test text boxes

**Expected behavior**
No syntax errors are shown

**Screenshots**
image

### PR DESCRIPTION
**Pull request by martinmladenov**
# Description of changes made
Fixed the bug where the tool window editors show an "Unexpected tokens" syntax error over all tests.

# Why is merge request needed
To fix the aforementioned bug

# Other notes
Closes #55

### CODE REVIEW

**Review by jzelenjak — DISMISSED** [review]
Good job! It works for me.

File: src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/TestCaseDisplayService.kt [hunk 1]
```diff
@@ -66,8 +65,7 @@ class TestCaseDisplayService(private val project: Project) {
             checkbox.isSelected = true
             testCasePanel.add(checkbox, BorderLayout.WEST)
 
-            val code = JavaCodeFragmentFactory.getInstance(project).createExpressionCodeFragment(testCode, null, null, true)
-            val document = PsiDocumentManager.getInstance(project).getDocument(code)
+            val document = EditorFactory.getInstance().createDocument(testCode)
```
Comment (kirilvasilev16) [inline src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/TestCaseDisplayService.kt:68]: I am getting the following exception:
```
java.lang.AssertionError: Wrong line separators: '\r\n  @Test(...' at offset 0
	at com.intellij.openapi.util.text.StringUtil.assertValidSeparators(StringUtil.java:2464)
	at com.intellij.openapi.editor.impl.DocumentImpl.assertValidSeparators(DocumentImpl.java:713)
	at com.intellij.openapi.editor.impl.DocumentImpl.<init>(DocumentImpl.java:122)
	at com.intellij.openapi.editor.impl.DocumentImpl.<init>(DocumentImpl.java:117)
	at com.intellij.openapi.editor.impl.DocumentImpl.<init>(DocumentImpl.java:108)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createDocument(EditorFactoryImpl.java:117)
	at nl.tudelft.ewi.se.ciselab.testgenie.services.TestCaseDisplayService.displayTestCases(TestCaseDisplayService.kt:68)
	at nl.tudelft.ewi.se.ciselab.testgenie.services.TestCaseDisplayService.showGeneratedTests(TestCaseDisplayService.kt:45)
	at nl.tudelft.ewi.se.ciselab.testgenie.listener.TestGenerationResultListenerImpl.testGenerationResult$lambda-0(TestGenerationResultListenerImpl.kt:21)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

Comment (martinmladenov) [reply src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/TestCaseDisplayService.kt]: Thanks, I'll look into it. It seems like a Windows-specific issue.

**Review by jzelenjak — APPROVED** [review]

**Review by kirilvasilev16 — APPROVED** [review]
