### PR TITLE
Fix caching service returning same test multiple times

### LINKED ISSUE #151: Caching service returns same test multiple times
**Describe the bug**
The caching service may return the same test multiple times if the test covers more than one line in the requested range.

**Expected behavior**
Each test should be returned only once in a single query.

**Screenshots**
N/A

**Additional context**
This was actually found while implementing #150 :smile:

### PR DESCRIPTION
**Pull request by martinmladenov**
# Description of changes made
 The caching service could return the same test multiple times if the test covers more than one line in the requested range.

# Why is merge request needed
To fix the bug

# Other notes
Closes #151 

This was actually found while implementing #150 :smile:

### CODE REVIEW

**Review by jzelenjak — APPROVED** [review]
LGTM! Thank you for fixing the bug. The test pass for me

File: src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/TestCaseCachingService.kt [hunk 1]
```diff
@@ -161,6 +161,26 @@ class TestCaseCachingService {
...
+            if (testName != other.testName) return false
+            if (testCode != other.testCode) return false
+            if (coveredLines != other.coveredLines) return false
+
+            return true
+        }
+
+        override fun hashCode(): Int {
+            var result = testName.hashCode()
+            result = 31 * result + testCode.hashCode()
```
Comment (bolkhod) [inline src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/TestCaseCachingService.kt:179]: Is there any specific reason for `31`?

Comment (martinmladenov) [reply src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/TestCaseCachingService.kt:179]: This is auto-generated code, having 31 here makes the hash function better (not sure what the exact math here is, this is what intellij generates).

**Review by bolkhod — APPROVED** [review]
LGTM
