### PR TITLE
Telemetry Path Bugfix

### LINKED ISSUE #155: Telemetry path chooser
**Describe the bug**
Once the telemetry option is enabled, the user should be able to specify the path where the telemetry should be saved. For convenience, the user is provided with a default path. However, the current implementation of the default path is not consistent and at times produces errors. Especially on arch btw...

**To Reproduce**
1. Go to Jegor.
2. Ask Jegor to launch "Run Plugin" with telemetry option enabled. 
3. An error will appear saying that something is wrong with telemetry path. 

**Expected behavior**
The error should not happen. To fix that, the idea of the default path will be scrapped in favor of file chooser which is empty by default. Prior to closing the settings there will be a check if telemetry is enabled and if the path is not empty, if path is empty inform the user that they need to choose it.  

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by SergeyDatskiv**
# Description of changes made
1. Replace the text field for the telemetry path with a text filed with a browse button. 
2. Delete the old default telemetry path settings.
3. Ensure that telemetry path can not be touched until the telemetry checkbox is set to true. 
4. In case the telemetry path is empty, reset the telemetry path back to previous state. 

# Why is merge request needed
The merge is needed in order to address the possible exception that is thrown on Jegor's, arch btw, machine. This will now set the default path to be user.home. Furthermore, the person can now choose the path through the file chooser. This should take care of all errors. 

# Other notes
Closes #155

*Please write if you have anything to add*
According to IntelliJ documentation the component responsible for path should have "filename completion", however this is not the case in this pull request. I suspect that this is because the feature is only allowing to select folders and not files, or because we do not provide a project variable. This is just a side note. Everything should be okay. 

# What is missing?
When the telemetry path is empty, the reset happens without informing the user that the reset occurred, i.e. no popup message is shown. This is done in order not to disturb the user in case the empty path was just a mistake. If needed the message can be added. 
 

- [x] I have checked that I am merging into correct branch

### CODE REVIEW

File: src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/settings/SettingsPluginConfigurable.kt [hunk 1]
```diff
@@ -68,9 +68,23 @@ class SettingsPluginConfigurable : Configurable {
         settingsState.buildPath = settingsComponent!!.buildPath
         settingsState.buildCommand = settingsComponent!!.buildCommand
         settingsState.telemetryEnabled = settingsComponent!!.telemetryEnabled
+        if (checkEmptyTelemetryPath(settingsState)) return
```
Comment (jzelenjak) [inline src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/settings/SettingsPluginConfigurable.kt:71]: Wouldn't it make sense to put this check at the start of the method?

File: src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/settings/SettingsPluginConfigurable.kt [hunk 2]
```diff
@@ -68,9 +68,23 @@ class SettingsPluginConfigurable : Configurable {
...
         settingsState.telemetryPath = settingsComponent!!.telemetryPath
     }
 
+    /**
+     * Check if the telemetry path is empty when telemetry is enabled.
+     * If empty, then sets to previous state. Else, keep the new one.
+     */
+    private fun checkEmptyTelemetryPath(settingsState: TestGenieSettingsState): Boolean {
+        if (settingsComponent!!.telemetryEnabled && settingsComponent!!.telemetryPath.isEmpty()) {
```
Comment (jzelenjak) [inline src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/settings/SettingsPluginConfigurable.kt:80]: Can you maybe change `isEmpty` to `isBlank`? Because blank strings are allowed right now

File: src/main/resources/defaults/TestGenie.properties [hunk 3]
```diff
@@ -14,4 +14,3 @@ buildPath=target/classes
 showCoverage=true
 buildCommand=mvn compile
 telemetryEnabled=false
-telemetryDirectory=TestGenieTelemetry
```
Comment (jzelenjak) [inline src/main/resources/defaults/TestGenie.properties:17]: I think that it is still better to keep this prefix so that we generate the files inside a directory, rather than just dump all the files by default in the home directory?
Maybe even make this directory hidden (aka starting with a dot)?

File: src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/settings/SettingsPluginComponent.kt [hunk 4]
```diff
@@ -48,7 +52,10 @@ class SettingsPluginComponent {
     )
     private val telemetrySeparator = JXTitledSeparator("Telemetry")
     private var telemetryEnabledCheckbox = JCheckBox("Enable telemetry")
-    private val telemetryPathTextField = JTextField(TestGenieSettingsState.DefaultSettingsState.telemetryPath)
+    private val fileChooserDescriptor = FileChooserDescriptor(false, true, false, false, false, false)
+    private val textBrowseFolderListener = TextBrowseFolderListener(fileChooserDescriptor)
+    private val telemetryPathChooser = TextFieldWithBrowseButton()
+    private val telemetryPathLabel = JBLabel("Specify the folder path for telemetry data")
```
Comment (jzelenjak) [inline src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/settings/SettingsPluginComponent.kt:58]: Right now OK button just quits the settings, but makes the field to be the home directory. Maybe you can at least specify to the user that the default is the home directory, so that such quitting would not be so surprising?

File: src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/settings/SettingsPluginConfigurable.kt (hunk 1 above)
Comment (SergeyDatskiv) [reply src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/settings/SettingsPluginConfigurable.kt:71]: I thought about it. IntellIj refactor did it that way, I figured it might be more readable for the developer if they see that there is a potential return statement in the main code body rather than in the helper function. 
It is not clean, but it is obvious that the following line will not be executed if the check passes.

File: src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/settings/SettingsPluginConfigurable.kt (hunk 2 above)
Comment (SergeyDatskiv) [reply src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/settings/SettingsPluginConfigurable.kt:80]: ok

File: src/main/resources/defaults/TestGenie.properties (hunk 3 above)
Comment (SergeyDatskiv) [reply src/main/resources/defaults/TestGenie.properties:17]: I will let @martinmladenov decide that one.

File: src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/settings/SettingsPluginConfigurable.kt (hunk 1 above)
Comment (jzelenjak) [reply src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/settings/SettingsPluginConfigurable.kt:71]: Alright (after some in-person discussion)

File: src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/settings/SettingsPluginComponent.kt (hunk 4 above)
Comment (SergeyDatskiv) [reply src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/settings/SettingsPluginComponent.kt:58]: Right now if the person left a blank line, then the path will be restored to the previous path. If the path was changed to path A, then it will be restored to path A not to home directory. 
The user should be able to see that the default is home directory when they first turn on telemetry. 
I wrote why I do not want to have pop us messages in my pull request description. 

"When the telemetry path is empty, the reset happens without informing the user that the reset occurred, i.e. no popup message is shown. This is done in order not to disturb the user in case the empty path was just a mistake. If needed the message can be added."

Comment (jzelenjak) [reply src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/settings/SettingsPluginComponent.kt:58]: Alright

**Review by jzelenjak — APPROVED** [review]

**Review by bolkhod — APPROVED** [review]

File: src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/settings/SettingsPluginConfigurable.kt [hunk 5]
```diff
@@ -68,9 +68,23 @@ class SettingsPluginConfigurable : Configurable {
...
+     */
+    private fun checkEmptyTelemetryPath(settingsState: TestGenieSettingsState): Boolean {
+        if (settingsComponent!!.telemetryEnabled && settingsComponent!!.telemetryPath.isBlank()) {
+            settingsState.telemetryPath = settingsState.telemetryPath
+            settingsComponent!!.telemetryPath = settingsState.telemetryPath
+            return true
+        }
+        return false
+    }
+
```
Comment (kirilvasilev16) [inline src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/settings/SettingsPluginConfigurable.kt:87]: Why do you need this check?

File: src/main/resources/defaults/TestGenie.properties (hunk 3 above)
Comment (martinmladenov) [reply src/main/resources/defaults/TestGenie.properties:17]: I think it doesn't really matter, the user is going to change the path anyways :)

**Review by martinmladenov — APPROVED** [review]
Amazing work, guys! :tada:

File: src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/settings/SettingsPluginConfigurable.kt (hunk 5 above)
Comment (SergeyDatskiv) [reply src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/settings/SettingsPluginConfigurable.kt:87]: As KDoc on top of the function says, this method is responsible for checking if the telemetry path field is empty, when the telemetry checkbox is enabled. If the path is empty and the user triggered the "apply" or "ok" buttons then the path will be reset to the previous saved path, if the path was entered, then it will be updated to the current one.

Comment (kirilvasilev16) [reply src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/settings/SettingsPluginConfigurable.kt:87]: I see.

**Review by kirilvasilev16 — APPROVED** [review]
