### PR TITLE
Fix method and class tests generation

### LINKED ISSUE #41: Fix Method and Class Tests generation
# Description
During our client meeting, we have discussed generating tests for classes and methods when clicking on them. The client has given us some feedback that we are going to incorporate in this issue (see Definition of Done)

Furthermore, the issue of generating tests for a class and a method from the last sprint must be continued: it is in its very basic version with a lot of limitations (overloads, java or third-party classes and methods). This will also be handled in this issue.

# Definition of Done
* [x] Instead of calling EvoSuite with the method prefix (which tests all overloads), *descriptors* are used so that only the selected method is tested
* [x] When clicking somewhere inside a class, there is an option to generate tests for that class
* [x] When clicking somewhere inside a method, there is an option to generate tests for that method
* [x] *NB! If the above 2 points turn out to be impossible to implement, the alternative would be to generate tests based on the clicked symbol*  
* [x] Classes and methods not from the current file are excluded

### PR DESCRIPTION
**Pull request by jzelenjak**
# Description of changes made
* Instead of calling EvoSuite with the method prefix (which tests all overloads), only the selected method is tested now
* When clicking somewhere inside a class, there is an option to generate tests for that class
* When clicking somewhere inside a method, there is an option to generate tests for that method
* Classes and methods not from the current file are excluded
* Interfaces, enums, anonymous classes are also excluded
* Action name changes depending on the selected class/method
* There is a separate class now called GenerateTestsUtils that stores some useful methods

# Why is merge request needed
This merge request is needed for two reasons:
1) It directly addresses the client's feedback
2) Generating tests is the essential part of TestGenie, and this merge request was fixing and improving the test generation process.

Closes #41 

# Other notes
 - Abstract classes etc have to be discussed with the client

# What is missing?

- [x] I have checked that I am merging into correct branch

### CODE REVIEW

File: src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/helpers/MethodDescriptorHelper.kt [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+import com.intellij.psi.PsiClassType
+import com.intellij.psi.PsiMethod
+import com.intellij.psi.PsiSubstitutor
+import com.intellij.psi.PsiType
+import com.intellij.util.containers.stream
+import java.util.stream.Collectors
+
+// Grammar taken from: https://docs.oracle.com/javase/specs/jvms/se11/html/jvms-4.html#jvms-4.3
+
+fun generateMethodDescriptor(psiMethod: PsiMethod): String {
```
Comment (kirilvasilev16) [inline src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/helpers/MethodDescriptorHelper.kt:12]: Please add KDoc to your methods.

**Review by kirilvasilev16 — CHANGES_REQUESTED** [review]
The test generation for method does not work if you are generating for a `void` method.

File: src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/helpers/MethodDescriptorHelper.kt (hunk 1 above)
Comment (martinmladenov) [reply src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/helpers/MethodDescriptorHelper.kt:17]: Done!

File: src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/evosuite/Runner.kt [hunk 2]
```diff
@@ -61,12 +61,14 @@ class Runner(
...
     /**
-     * Sets up evosuite to run for a target method of the target class. This attaches a method prefix argument
+     * Sets up evosuite to run for a target method of the target class. This attaches a method descriptor argument
      * to the evosuite process.
+     *
+     * @param methodDescriptor The method descriptor of the method under test
      */
-    fun forMethod(method: String): Runner {
+    fun forMethod(methodDescriptor: String): Runner {
         command =
```
Comment (bolkhod) [inline src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/evosuite/Runner.kt:70]: What is the key difference between you using `method` and `methodDescriptor`?

File: src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/helpers/MethodDescriptorHelperTest.kt [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+    @ParameterizedTest
+    @MethodSource("primitiveFieldTypeTestGenerator")
+    fun primitiveFieldTypeTest(text: String, expected: String) {
+        val psiType = PsiJavaParserFacadeImpl.getPrimitiveType(text)
+        assertThat(generateFieldType(psiType)).isEqualTo(expected)
+    }
+
+    companion object {
+        @JvmStatic
+        private fun primitiveFieldTypeTestGenerator(): Stream<Arguments> {
```
Comment (bolkhod) [inline src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/helpers/MethodDescriptorHelperTest.kt:21]: Is this the odd "Java descriptor" thing you've been talking about that hardcodes some types to letters?

File: src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/actions/GenerateTestsUtils.kt [hunk 4]
```diff
@@ -0,0 +1,163 @@
...
+     * @param psiFile the current PSI file (where the user makes a click)
+     * @param caret the current (primary) caret that did the click
+     * @return PsiClass element if it has been found, null otherwise
+     */
+    fun getSurroundingClass(psiFile: PsiFile, caret: Caret): PsiClass? {
+        // Get the classes of the PSI file
+        val classElements = PsiTreeUtil.findChildrenOfAnyType(psiFile, PsiClass::class.java)
+
+        // Get the surrounding PSI class (i.e. the cursor has to be within that class)
+        var surroundingClass: PsiClass? = null
```
Comment (bolkhod) [inline src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/actions/GenerateTestsUtils.kt:31]: can't you stop the loop when you found the first hit?

File: src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/actions/GenerateTestsActionClass.kt [hunk 5]
```diff
@@ -18,32 +20,42 @@ class GenerateTestsActionClass : AnAction() {
...
+
+        val psiClass: PsiClass = GenerateTestsUtils.getSurroundingClass(psiFile, caret) ?: return
+        val classFQN = psiClass.qualifiedName ?: return
+
         val projectPath: String = ProjectRootManager.getInstance(project).contentRoots.first().path
         val projectClassPath = "$projectPath/target/classes/"
 
         log.info("Generating tests for project $projectPath with classpath $projectClassPath")
 
-        val psiClass = e.dataContext.getData(CommonDataKeys.PSI_ELEMENT) as PsiClass // Checked in update method
```
Comment (bolkhod) [inline src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/actions/GenerateTestsActionClass.kt:32]: why did you move this several lines up?

File: src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/evosuite/Runner.kt (hunk 2 above)
Comment (jzelenjak) [reply src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/evosuite/Runner.kt:70]: I think that `method` is a method prefix, while `methodDescriptor` is the entire method signature.

File: src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/helpers/MethodDescriptorHelperTest.kt (hunk 3 above)
Comment (jzelenjak) [reply src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/helpers/MethodDescriptorHelperTest.kt:21]: Yes. There is a context-free-grammar for it

File: src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/actions/GenerateTestsUtils.kt (hunk 4 above)
Comment (jzelenjak) [reply src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/actions/GenerateTestsUtils.kt]: No, otherwise you will ignore the nested things, like e.g nested static classes

File: src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/actions/GenerateTestsActionClass.kt (hunk 5 above)
Comment (jzelenjak) [reply src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/actions/GenerateTestsActionClass.kt:32]: I think that i was changing a lot of stuff in this method and in the end ended up with that order. But i like it more

File: src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/evosuite/Runner.kt (hunk 2 above)
Comment (bolkhod) [reply src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/evosuite/Runner.kt:70]: what is the key difference that made you switch

File: src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/actions/GenerateTestsUtils.kt (hunk 4 above)
Comment (bolkhod) [reply src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/actions/GenerateTestsUtils.kt]: aaaaaaaaaaa, got it 👍

File: src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/evosuite/Runner.kt (hunk 2 above)
Comment (jzelenjak) [reply src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/evosuite/Runner.kt:70]: With method prefix, EvoSuite will generate tests for all the overloads of the given method name. With descriptor - only for the selected one, since the method signature is unique

**Review by bolkhod — APPROVED** [review]
Great functional additions that work on my machine. I like how you guys changed the way of testing methods. I also like the intuitive restrictions.

**Review by kirilvasilev16 — APPROVED** [review]
